### ISSUE TITLE
RuntimeError: Given groups=3, expected weight to be divisible by 3 at dimension 0, but got weight of size [[128, 1, 2, 2]] instead

### ISSUE THREAD

**Issue by Ifjmww** [BGU-CS-VIL/WTConv#34]
Hi,
WTConv is a very interesting and meaningful job. And I want to use WTConv module for the image preprocessing part. I wrote the following program to test whether WTConv works.
```
from wtconv import WTConv2d
import torch

inputs = torch.randn(1, 3, 224, 224)
model = WTConv2d(32, 32, kernel_size=5, wt_levels=2)
outputs = model(inputs)
```
However, the program prompts the following error:
```
Traceback (most recent call last):
  File "C:\Users\IFJMWW\Desktop\paper\WTConv\test.py", line 6, in <module>
    outputs = model(inputs)
  File "H:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\IFJMWW\Desktop\paper\WTConv\wtconv\wtconv2d.py", line 57, in forward
    curr_x = wavelet.wavelet_transform(curr_x_ll, self.wt_filter)
  File "C:\Users\IFJMWW\Desktop\paper\WTConv\wtconv\util\wavelet.py", line 34, in wavelet_transform
    x = F.conv2d(x, filters, stride=2, groups=c, padding=pad)
RuntimeError: Given groups=3, expected weight to be divisible by 3 at dimension 0, but got weight of size [[128, 1, 2, 2]] instead
```

How can I solve it?
thank you

**Comment by shahaffind** [comment]
Hi,
It seems like you are using input with 3 channels on a model with input channels=32

**Comment by Ifjmww** [comment]
Thank you for your answer, my problem has been solved
