### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by VictorWild** [BGU-CS-VIL/WTConv#35]
Sorry to bother,professor.I'm trying to run the original train.py using the command below:
```
python train.py --model wtconvnext_tiny --drop-path 0.1 \
                --data-dir MY_DATA_PATH \
                --epochs 300 --warmup-epochs 20 \
                --batch-size 64 --grad-accum-steps 64 --sched-on-updates \
                --lr 4e-3 --weight-decay 5e-2 \
                --opt adamw --layer-decay 1.0 \
                --aa rand-m9-mstd0.5-inc1 \
                --reprob 0.25 --mixup 0.8 --cutmix 1.0 \
                --model-ema --model-ema-decay 0.9999 \
                --output my_outputpath/
```
But I encountered a bug like this:
```
Traceback (most recent call last):
  File "/opt/Projects/ysy/WTConv-main/train.py", line 1181, in <module>
    main()
  File "/opt/Projects/ysy/WTConv-main/train.py", line 559, in main
    optimizer = create_optimizer_v2(
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/lab721/anaconda3/envs/ysy/lib/python3.12/site-packages/timm/optim/optim_factory.py", line 235, in create_optimizer_v2
    parameters = param_groups_layer_decay(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab721/anaconda3/envs/ysy/lib/python3.12/site-packages/timm/optim/optim_factory.py", line 108, in param_groups_layer_decay
    no_weight_decay_list = set(no_weight_decay_list)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```
I wonder if it's a version mismatch problem.The pytorch I use is 2.2.0. The rest is the same as requirements.
I would greatly appreciate it if I can get some help from you.

**Comment by shahaffind** [comment]
Which timm version are you using?

**Comment by VictorWild** [comment]
> Which timm version are you using?
It's 1.0.7

**Comment by VictorWild** [comment]
> Which timm version are you using?

It's 1.0.7

**Comment by 12138wa** [comment]
> > 您使用的是哪个 timm 版本？
> 
> 这是 1.0.7

Hello, have you solved this problem? How did you resolve it? I am also encountering the same issue.
